version: "2"

services:
    php:
        volumes:
            - '.:/srv'
        environment:
            - SYMFONY_ENV=dev
            - PHP_IDE_CONFIG=serverName=docker
            - USER_ID=${USER_ID}

    front:
        ports:
            - 0.0.0.0:8080:80

    database:
        volumes:
            - dbdata:/var/lib/postgresql

volumes:
    dbdata:
        driver: local
