security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        App\Entity\User: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    role_hierarchy:
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_CAN_UPLOAD_FILE]

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~
            anonymous: true

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET]}
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }