#!/usr/bin/env bash

COMPOSE_FILE=docker-compose.yml:support/docker-compose.test.yml

# Run phpspec tests
docker-compose run --user $(id -u) --no-deps php bin/phpspec run && \

# Run integration/E2E tests
docker-compose up --no-deps -d database && \
docker-compose run --user $(id -u) --rm --no-deps php bin/healthcheck 10 && \
docker-compose run --user $(id -u) --rm --no-deps php bin/behat

if [ $? -eq 0 ]
then
  echo "Tests passed!"
else
  echo "Tests failed!" >&2
fi

# Cleanup after tests
docker-compose kill && \
docker-compose rm --all -f
